"""Citation validation utilities.

Validates that citations generated by an LLM accurately map to
the provided retrieval context, detecting fabricated or hallucinated citations.
"""

from __future__ import annotations

import re


class CitationValidator:
    """Validates generated citations against context."""

    def __init__(self, citation_pattern: str = r"\[(\d+)\]") -> None:
        """Initialize the validator.

        Args:
            citation_pattern: Regex pattern to extract citations from text.
                              Default extracts numeric markers like [1], [2].
        """
        self.citation_pattern = re.compile(citation_pattern)

    def extract_citations(self, text: str) -> list[str]:
        """Extract citation markers from text."""
        return self.citation_pattern.findall(text)

    def validate_citations(self, actual_output: str, retrieval_context: list[str]) -> dict[str, float]:
        """Validate if the citations refer to valid context indices.

        Assuming citations like [1], [2] map to retrieval_context[0], retrieval_context[1].
        If your system uses string doc IDs like [doc_id], you would adjust this
        to check against a map of doc_id -> context.

        Returns:
            A dictionary containing:
                - total_citations: Number of citations found.
                - valid_citations: Number of citations that point to existing context.
                - citation_accuracy: Ratio of valid to total (1.0 if no citations).
        """
        citations = self.extract_citations(actual_output)

        if not citations:
            return {
                "total_citations": 0.0,
                "valid_citations": 0.0,
                "citation_accuracy": 1.0,  # No citations means no fabricated citations
            }

        valid_count = 0
        for cite in citations:
            try:
                # 1-indexed citations mapped to 0-indexed context list
                idx = int(cite) - 1
                if 0 <= idx < len(retrieval_context):
                    valid_count += 1
            except ValueError:
                # Non-numeric citation, mark invalid if we expected numeric
                pass

        return {
            "total_citations": float(len(citations)),
            "valid_citations": float(valid_count),
            "citation_accuracy": valid_count / len(citations),
        }
